name: dev
base: ubuntu@24.04
sdks:
  - name: project-base
  - name: vscode-remote
  # - name: opencode
  #   channel: latest/stable
  - name: copilot
    channel: latest/stable
  # - name: rust
  #   channel: latest/stable
  - name: node
    channel: 24/stable

actions:
  # opencode: opencode "$@"
  copilot-yolo: copilot --yolo --interactive="$@"
  copilot-yolo-prompt: copilot --yolo --prompt="$@"
